ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255) NULL AFTER mobile,
  ADD COLUMN IF NOT EXISTS email VARCHAR(255) NULL AFTER contact_person,
  ADD COLUMN IF NOT EXISTS address VARCHAR(500) NULL AFTER email;
